/**
 * Id-only datacard for the selected unit: the Svelte side resolves profiles,
 * weapons, abilities (with generated effect text), and keywords from the
 * embedded 40kdc dataset by id. `datasheet_id == null` means the unit never
 * resolved — the card degrades to the raw unit name plus `loadout_raw_names`
 * instead of going blank.
 *
 * In the host app this type is generated by ts-rs from the Rust bridge; here it
 * is hand-maintained, since the builder produces it directly from the dataset
 * (see `builderUnitToDatacardData` in `$lib/data/builder`).
 */
export type DatacardData = {
	unit_name: string;
	player: string;
	datasheet_id: string | null;
	/**
	 * Owning faction of `datasheet_id`, used to resolve the correct copy of a
	 * datasheet shared across factions (e.g. the Chaos chassis under the cult
	 * legions, where each faction's copy has different keywords/profiles/points).
	 * Null when the source has no faction context (degraded imports) — the card
	 * then falls back to a faction-less first-wins lookup.
	 */
	faction_id?: string | null;
	/**
	 * Loadout-filtered weapon ids in canonical ranged/melee order.
	 */
	ranged_weapon_ids: Array<string>;
	melee_weapon_ids: Array<string>;
	/**
	 * Raw loadout text for the unresolved-unit fallback card.
	 */
	loadout_raw_names: Array<string>;
};
